### ISSUE TITLE
Hi team, can you send a document or Example ??

### ISSUE THREAD

**Issue by bachlongkocanh** [MetaMask/metamask-mobile-provider#7]
I have tried using your library. After injecting dist / index.js file into dapp, I received a message with method "wallet_sendDomainMetadata". I don't know how to declare rpcUrl, chainId, selectAddress ... Can you send a document or Example ?? Thank!!

**Comment by rekmarks** [comment]
Hi @bachlongkocanh, this module is only designed to work directly with the MetaMask mobile app. Because of that, I'm afraid we don't have many examples of how to use it.

That said, I'd like to help you if I can! Can you provide any more details of what you're trying to accomplish?
